### ISSUE TITLE
Fix link Introducing collective.taxonomy

### ISSUE THREAD

**Issue by rodfersou** [collective/collective.taxonomy#101]
In the README we have a link to a post that is not online anymore, but we can find a "backup" at web archive:

https://web.archive.org/web/20160324000054/http://bo.geekworld.dk/introducing-collective-taxonomy/

So we could or republish it somewhere, or merge their text with another documentation

**Comment by petschki** [comment]
I've just removed it now, because there were ReST errors during release ... I think this is obsolete since your new tutorial
