### ISSUE TITLE
Package lacks tests

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.taxonomy#11]
This package looks very promising but without proper testing is going to be difficult to evaluate it at first without some fear.

I just added a CI configuration so we can start working on this: https://github.com/collective/collective.taxonomy/compare/ab489ae8f7...ea02804804

**Comment by vincentfretin** [comment]
The package is now tested on travis for Plone 4.3, 5.0 and 5.1. Sure not all the code is tested. Feel free to create a PR to add some more.
