### ISSUE TITLE
egg size

### ISSUE THREAD

**Issue by avoinea** [collective/collective.taxonomy#116]
The latest egg on pypi container a cypress video of `57.5Mb`:

`collective.taxonomy-2.1.0/src/collective/taxonomy/javascripts/cypress/videos/end_to_end.js.mp4`

**Comment by avoinea** [comment]
@petschki @ale-rt Can we have a release with these changes?

**Comment by petschki** [comment]
@avoinea done! https://pypi.org/project/collective.taxonomy/
