### ISSUE TITLE
plone.synchronize is missing, in the default Plone6 Installation the import is broken

### ISSUE THREAD

**Issue by 1letter** [collective/collective.taxonomy#120]
Whats the preferred way?

plone.synchronize should added to setup.py in the 'install_requires' - section

or

alternative an import from [plone.dexterity](https://github.com/plone/plone.dexterity/blob/master/plone/dexterity/synchronize.py#L1) >= 2.10.5

**Comment by yurj** [comment]
```
try:
    # Plone 6
    from plone.dexterity.synchronize import synchronized
except ImportError:
    # Plone 5
    from plone.syncronize.decorator import synchronized
```
