### ISSUE TITLE
2.2.0 release CHANGES is wrong

### ISSUE THREAD

**Issue by alecghica** [collective/collective.taxonomy#128]
The 2.2.0 is broken as does not contain the latest modification that for example documented under https://github.com/collective/collective.taxonomy/blob/master/CHANGES.rst#220-2021-12-13.

For example the changes done by Petchesi-Iulian via https://github.com/collective/collective.taxonomy/pull/113 are not included.

**Comment by alecghica** [comment]
@petschki can you please fix this?

**Comment by petschki** [comment]
not broken, but the changes in #113 were merged (2021-12-28) after the release (https://pypi.org/project/collective.taxonomy/2.2.0/ 2021-12-13) without updating the CHANGES.txt ... I recommend @Petchesi-Iulian to cleanup the CHANGES.txt and then I can do a `2.2.1` release.

**Comment by alecghica** [comment]
@petschki release 2.2.1 can be done anytime now if ask me.
I'll close this issues as it's done.

**Comment by petschki** [comment]
done https://pypi.org/project/collective.taxonomy/2.2.1/
