### ISSUE TITLE
Taxonomy configlet should be available to Site Administrators

### ISSUE THREAD

**Issue by laulaz** [collective/collective.taxonomy#134]
I see no reason why taxonomy configlet (and taxonomy edition) should be restricted to Managers (`Manage portal` / `cmf.ManagePortal` permissions).
I plan to make a pull request to add a new permission for taxonomy configlet to allow Managers & Site Administrators.

Don't hesitate if you have any objection to this ...

**Comment by petschki** [comment]
fixed in release `2.2.2`  ... I'll prepare a second PR with plon6 only changes and major version bump

**Comment by laulaz** [comment]
thanks a lot for the work @petschki
