### ISSUE TITLE
Taxonomies icon in Control Panel seems broken on Plone 6

### ISSUE THREAD

**Issue by avoinea** [collective/collective.taxonomy#135]
![taxonomies-icon](https://user-images.githubusercontent.com/323385/176912204-67e8f72b-2982-4fe6-8c4e-08699ee8f82d.png)

**Comment by petschki** [comment]
In Plone 6.0 the `icon_expr` was reactivated for `ActionItem` ... needs to be updated here. 

@laulaz Could you take care of that in your PR (https://github.com/collective/collective.taxonomy/pull/136) too since you've an upgrade step there?

**Comment by petschki** [comment]
See example of default control panel item here https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/profiles/default/controlpanel.xml#L6 ... you can simply but the name of a Bootstrap 5 icon with `string:` prefixed there.

**Comment by laulaz** [comment]
> @laulaz Could you take care of that in your PR (#136) too since you've an upgrade step there?

Done 👍

**Comment by petschki** [comment]
fixed in `3.0.0a1`
