### ISSUE TITLE
AttributeError: 'TaxonomyBehavior' object has no attribute 'former_dotted_names' 

### ISSUE THREAD

**Issue by erral** [collective/collective.taxonomy#139]
See https://github.com/plone/plone.behavior/issues/23

I think we need to add `former_dotted_names` to the behaviors created by collective.taxonomy here https://github.com/collective/collective.taxonomy/blob/master/src/collective/taxonomy/behavior.py#L45

**Comment by petschki** [comment]
Fixed in #169 -> released 3.1.5

Maybe someon wants to backport this?
