### ISSUE TITLE
New package release

### ISSUE THREAD

**Issue by laulaz** [collective/collective.taxonomy#141]
@petschki would it be possible to make a new package release ?
or give me the right to do it on PyPi (user : laz) ?

🙏

**Comment by petschki** [comment]
I can make a release but cannot assign new collaborators ...  unfortunately. @malthe maybe?

**Comment by petschki** [comment]
done https://pypi.org/project/collective.taxonomy/

**Comment by laulaz** [comment]
Big thanks @petschki
