### ISSUE TITLE
enable plone.app.widgets for TaxonomySelectWidget

### ISSUE THREAD

**Issue by petschki** [collective/collective.taxonomy#15]
is there a special usecase why you use a custom TaxonomySelect[Field]Widget ?
I'm asking, because I'm using p.a.widgets and would really like to have the SubjectsFieldWidget UI for taxonomy.

My first step was to disable your widget here https://github.com/collective/collective.taxonomy/blob/master/src/collective/taxonomy/behavior.py#L181 and got nice orderable default widgets:
![bildschirmfoto 2014-12-03 um 19 00 26](https://cloud.githubusercontent.com/assets/511761/5285731/ac2fb1c0-7b1e-11e4-999d-f861bbfe88a0.png)
well not so bad ...
but now I'm stuck in the p.a.widgets magic of overriding default widgets ... 

@thet @bosim do you have any pointers, how I can get this to work?

**Comment by vincentfretin** [comment]
@petschki It seems that the TaxonomySelectWidget inherits from OrderedSelectWidget and have custom template that look like a lot to the one from default z3cform Set widget (same as your capture, but without the up and down arrow.) I'm not sure why the author did that.

I did a new widget with Eric Bréhault based on select2 that regroup level2 terms for a 2-level taxonomy and I had to monkey patch the taxonomy widget like this https://github.com/collective/collective.z3cform.select2/commit/d93345d19ced97487484cae20f371958aa332680#diff-1ac4e1234c174293d6613bfbb44b458cR32
https://github.com/collective/collective.z3cform.select2

**Comment by vincentfretin** [comment]
I'm not sure we need to do something here. I'm closing the issue for inactivity. Feel free to reopen to discuss.
