### ISSUE TITLE
Someone could make a release ?

### ISSUE THREAD

**Issue by bsuttor** [collective/collective.taxonomy#20]
Hello,

There are lots of improvements with this PR : https://github.com/collective/collective.taxonomy/pull/18

Is there someone how can make release of it ? Or give me right to do it ? (my pypi user is bsuttor)
I see that package index owner are : @bosim @malthe @sunew @tmog 

Thank you ;)

**Comment by malthe** [comment]
@bsuttor, I see that @tomgross merged that pull requests.

I think it's great that @cedricmessiant contributed this app, but I can't assess how easily it fits into Plone and if it can be maintained by the "collective". I remember that the original intention of ``collective.taxonomy`` was to make something pretty simple.

**Comment by vincentfretin** [comment]
It was impossible to translate terms of a taxonomy with the previous dynatree UI. And writing an UI with jQuery and keeping the changes on the browser until you click Save seemed complex to do.

We decided to rewrite a UI based on one of the most stable, supported and popular javascript framework at the time, and still is today, which is react with redux, with npm, babel and webpack for the bundle. There are several developers with this js skills and are using collective.taxonomy in several projects, so I'm sure if there is an issue with the new interface, we will be able to fix them.

**Comment by malthe** [comment]
I have added ``vincentfretin`` as maintainer on PyPi for this package.

**Comment by vincentfretin** [comment]
Thanks @malthe, I did the release 1.3.0
