### ISSUE TITLE
Taxonomy editor does save changes Plone5.0.6

### ISSUE THREAD

**Issue by chervol** [collective/collective.taxonomy#30]
collective.taxonomy-1.4.2.
plone.app.multilingual-4.0.3

JS console output upon clicking Submit button:

(index):8614 POST http://localhost:8080/Plone/undefined/@@taxonomy-import 404 (Not Found)
spinner.gif:1 GET http://localhost:8080/Plone/undefined/spinner.gif 404 (Not Found)

Back to Settings leads to another 404 http://localhost:8080/Plone/undefined/@@taxonomy-settings

There are nice icons on taxonomy edit screen but no hints about their functionality. Have not found "delete node".

**Comment by vincentfretin** [comment]
I released 1.4.3 with the latest fix for Plone 5, please test this version. The only remaining issue I see is https://github.com/collective/collective.taxonomy/issues/32

**Comment by vincentfretin** [comment]
I released 1.4.4 which fix taxonomy export.

**Comment by chervol** [comment]
Works nicely in my stock Plone-5.0.6.  Thank You!

**Comment by vincentfretin** [comment]
Great, I'm glad.
