### ISSUE TITLE
Taxonomy doesn't appear on default Document view on Plone 5

### ISSUE THREAD

**Issue by vincentfretin** [collective/collective.taxonomy#32]
I enable the test taxonomy on the Document content type.
I create a document and I select some terms in the test taxonomy in the Categorization tab.
I save.
The field doesn't appear on the default view, like it do on Plone 4.3.

@tomgross Do you have an idea of what the problem is? Is this a bug in Plone 5?

**Comment by tomgross** [comment]
@vincentfretin The default document view of plone.app.contenttypes is very minimal. https://github.com/plone/plone.app.contenttypes/blob/master/plone/app/contenttypes/browser/templates/document.pt
I guess you have to override it to include the taxonomy field or even for a generic view of all (behavior)fields.

**Comment by vincentfretin** [comment]
Ah. Indeed with a custom content type, the Categorization fieldset appears. Thanks.
