### ISSUE TITLE
Problem with slash in title

### ISSUE THREAD

**Issue by rristow** [collective/collective.taxonomy#34]
Problem:
If you add a Taxonomy with a slash in title, for example:  "first / second".
The first part of the title will be removed and the item could be registered in the wrong level.

Analyse:
It seems that the "PATH_SEPARATOR" (collective.taxonomy/src/collective/taxonomy/__init__.py) is related with the problem.

**Comment by vincentfretin** [comment]
Yeah, the slash is used to generate the full identifier of a term of level above one. If you really want to use slash in term title, you can monkey patch this constant.
In one of your module, you can use for example:
```
import collective.taxonomy
collective.taxonomy.PATH_SEPARATOR = '->'
```
I think you need to reimport your taxonomy after that if you still want the ' » ' as separator when visualizing  the taxonomy through the widget (for this code to work
https://github.com/collective/collective.taxonomy/blob/de4271760d6110597a56c807b01b8738c06829fa/src/collective/taxonomy/utility.py#L180)

**Comment by rristow** [comment]
I'll ask you to reconsider this, because it will not be possible for a 'regular user' to add a description like, e.g. "In/Ou process" and this is in my opinion a huge limitation.
Or use a scape char,  like "\"

**Comment by vincentfretin** [comment]
Ok, we can maybe change the default used separator, do an upgrade step to fix existing taxonomies if needed.

**Comment by cedricmessiant** [comment]
We had the same issue, that's why I introduced the `PATH_SEPARATOR` constant. So I agree that we should change the default separator with something that is less likely to appear in terms.

**Comment by malthe** [comment]
I think we can simply have a versioning flag on the taxonomy object and then have a migration step. That is, we'll have a compatibility mode such that migration is not required.
