### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'getGeneratedName'

### ISSUE THREAD

**Issue by spanish** [collective/collective.taxonomy#37]
Hello,

I can't edit taxonomies with collective.taxonomy 1.2.3 on Plone 4.3.10 (using .xml VDEX files).

Taxonomies -> check any taxonomy -> Edit taxonomy -> Save -> get the below error:

Traceback (innermost last):
Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module z3c.form.form, line 233, in __call__
Module z3c.form.form, line 226, in update
Module plone.z3cform.patch, line 21, in BaseForm_update
Module z3c.form.form, line 154, in update
Module collective.taxonomy.controlpanel, line 194, in updateWidgets
Module z3c.form.form, line 129, in updateWidgets
Module collective.taxonomy.controlpanel, line 198, in getContent
Module collective.taxonomy.controlpanel, line 258, in __init__
AttributeError: 'NoneType' object has no attribute 'getGeneratedName'

Any idea to solve this?

Thanks!

Manuel

**Comment by vincentfretin** [comment]
Please use a recent version. I suggest you version 1.4.2 before we use lxml (I have an issue with lxml with 1.4.4, I need to look into it)

**Comment by spanish** [comment]
This solves the problem. Thank you very much! Manuel
