### ISSUE TITLE
this needs a release!

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.taxonomy#39]
...since this is Plone 5.0 and 5.1 compatible

**Comment by tomgross** [comment]
@tkimnguyen A release compatible with Plone 5.0 and 5.1 is out: https://pypi.python.org/pypi/collective.taxonomy/1.4.4
There are no major changes in master since then or did I miss something?

**Comment by tkimnguyen** [comment]
Ah, sorry @tomgross, I scrolled down the README and saw "Requirements: Plone 4.3". For Plone 5 compatible add-ons I've been adding a section near the top of the README called "Plone Version Compatibility" and listing Plone 5, but of course anything you prefer works.

**Comment by tkimnguyen** [comment]
I had been reading some old forum messages, https://community.plone.org/t/i-want-the-ability-to-create-vocabularies-ttw/1598/28

**Comment by vincentfretin** [comment]
Yes, the trove classifiers was up to date, but not the README. Thanks for the PR.
