### ISSUE TITLE
Exception when add page with taxonomy behavior

### ISSUE THREAD

**Issue by rodfersou** [collective/collective.taxonomy#80]
```python
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 156, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 338, in publish_module
  Module ZPublisher.WSGIPublisher, line 256, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 62, in call_object
  Module plone.z3cform.layout, line 63, in __call__
  Module plone.z3cform.layout, line 47, in update
  Module plone.dexterity.browser.add, line 141, in update
  Module plone.z3cform.fieldsets.extensible, line 65, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 141, in update
  Module z3c.form.group, line 52, in update
  Module z3c.form.group, line 48, in updateWidgets
  Module z3c.form.field, line 277, in update
  Module collective.taxonomy.widget, line 39, in update
  Module z3c.form.browser.orderedselect, line 54, in update
  Module z3c.form.browser.orderedselect, line 54, in <listcomp>
  Module z3c.form.browser.orderedselect, line 45, in getItem
  Module zope.i18n, line 194, in translate
  Module collective.taxonomy.utility, line 296, in translate
KeyError: 'en-us'
```

**Comment by rodfersou** [comment]
Using Python 3 and Plone 5.2

**Comment by rodfersou** [comment]
looks like it is waiting `en` but the language is `en-us`:

```python
> /home/rodrigo/projects/collective/collective.taxonomy/src/collective/taxonomy/utility.py(297)translate()
-> if msgid not in self.inverted_data[target_language]:
(Pdb) msgid
'd5p0h0rqlv'
(Pdb) target_language
'en-us'
(Pdb) self.inverted_data
{'en': {'dak687egh8': '␟Companies', '1nuysps3lh': '␟Companies␟Coca Cola', 'x9ymi2do73': '␟Companies␟Pepsi', 'd5p0h0rqlv': '␟Museum', 'p3owj0qkga': '␟Museum␟France', 'a0qw550ajh': '␟Museum␟Germany', '6aaeopvueg': '␟Museum␟Netherlands'}}
```

**Comment by rodfersou** [comment]
After change the default language to `English` start to work;

But I'll keep the issue open while the default value is not the current selected language in Multilingual

**Comment by agitator** [comment]
I think I remember that problem... happened (in a multilingual site) when a term is not translated in all configured languages.
A fallback to the main term for this would nice.

**Comment by rodfersou** [comment]
List of languages are not matching between p.a.multilingual and c.taxonomy, we need to use portal_languages to have same source of truth

**Comment by petschki** [comment]
There are some cases, where this happens. I just startet to fix following:

1. refactor c.taxonomy's language vocabulary to `plone.app.vocabularies.languages`
2. catch error in translation when default language is switched on portal (defaults then to the first existing taxonomy language)
3. Fix cases, when the taxonomy was created in a language which doesn't exists after changing global language settings. The already created language is then still visible in the taxonomy edit view.

there might be some other cases which aren't fixed right now. I create a PR today and you're feedback will be welcome.
