### ISSUE TITLE
new release 2.0.1

### ISSUE THREAD

**Issue by petschki** [collective/collective.taxonomy#99]
the latest changes improve multilanguage handling a lot.
@rodfersou whats the state of the documentation? ready for release? otherwise I'd recommend to release 2.0.1 with the current changes.

/cc @ericof @malthe (or me if someone give me rights 😄 )

**Comment by rodfersou** [comment]
please go on with the release

**Comment by malthe** [comment]
@petschki I have added you as a maintainer.

**Comment by petschki** [comment]
done
